### ISSUE TITLE
Command sign macros

### ISSUE THREAD

**Issue by schismatix** [Philipp15b/MagicSigns#12] opened 2013-05-21 07:06 UTC
Been playing about with this great plugin it has endless possibilities however....
I have created a macro in the config to basically clear an inventory and then teleport to a location. I then go to put the macro on a [ccommand] sign but I cannot create one as it states All commands must begin with a slash and creates a blank sign. I am encasing the macro in $ as stated in the wiki, even if placed after another comand with the && it still gives the same result. I have tried numerous different commands in the config even standard ones like /give and /time but to no avail.The config file is set out like this:
command-macros:
    ARENATP:
    - /clearinventory %p 
    - /tppos %p 243 51 401 180

and the sign I try to put up:
[ccommand]
$ARENATP$

**Comment by Philipp15b** [comment] 2013-05-21 07:58
Hello, thanks for reporting this issue. It doesn't look like you did anything wrong. Unfortunately, I have real trouble reproducing this. I remember trying this yesterday and it would work for me with the macro name `TEST`, but not `TESTTEST`. `ARENATP` would also not work. `ABCDEF` would work, `ABCDEFG` would not work and I was pretty sure that there was somehow a limit of 6 characters maximum as the macro name (not that I knew how that could ever happen unintentionally). Now the fun part: After I started my debugging environment, I haven't been able to reproduce this ever since. I have no idea why this won't work again for me.

Could you please try it with the macro names I listed above too? Thanks.

**Comment by schismatix** [comment] 2013-05-21 09:03
Ok, I don't think this is going to make things any clearer. I started to test with the macro names you requested as follows TEST - worked, TESTTEST gave the error, ABCDEF worked ABCDEFG gave the error. I then tried ARENATP but made a typo and got an error when restarted the server. So as this had happened I redid the whole test from the beginning and the weird part they are all working including arenatp. Stupidly I didnt write down the error but it was to do with me missing a colon I think. I will continue to see if I can replicate the Ccommand requires a slash error and report back

**Comment by schismatix** [comment] 2013-05-21 09:32
OK with a config containing the following macros:
  ARENATP:
  TESTTEST:
  ABCDEF:
  ABCDEFG:
  12345:
  1234567:
  TEST:
  TESTTESTTEST:

everything works so I'm really confused but I'm not going mad.....at least I don't think so......I could not get it to work before the error in the config as it did keep saying that ccommand required a slash.
Now all I've got to do is get the damn clearinventory to work as it only seems to clear the inventory with a relog.
Sorry to cause confusion hope someone else can replicate the problem and assist further.
Schis

**Comment by Philipp15b** [comment] 2013-05-21 09:36
I still don't know what this is caused by, but I got two ideas:
1. The error also appears every time a macro is not found - this should be improved.
2. Before I started my debugging environment, I must have used only `/ms reload` which apparently doesn't reload the macros properly. I'll have to look into that. This may explain why I got the error.

Don't worry that you're going mad - at least you're not alone :smirk: 

If this works now, I'll close this issue - but please report back if you find any errors again.

Thanks for helping!

**Closed as completed by Philipp15b** 2013-05-21 09:36 UTC

**Comment by Philipp15b** [comment] 2013-05-21 13:03
Just a note: I just completely rewrote the macro and command parsing (https://github.com/Philipp15b/MagicSigns/commit/1745f8ea79ea12437d1490daec690297873f8362) and also added automated testing. At least now they don't show any problems, even with long macro names. So if there was an issue, it was probably fixed. I also added _much_ better error reporting.
