### ISSUE TITLE
Using spaces with commands

### ISSUE THREAD

**Issue by edster** [Philipp15b/MagicSigns#2] opened 2012-06-22 05:22 UTC
I'm trying to use magicsigns to make joining my arenas automatic instead of having to type it out.

I'm using

[COMMAND]
/ma join dome

But the console then says, invalid command type /help
when I type /ma join dome manually into the console it works fine, is there something I'm doing wrong?

**Comment by Philipp15b** [comment] 2012-06-24 17:32
Hmm, maybe this is caused by unnormal command registration of the plugin you are using. Then the command could only be used via the chat.

**Comment by edster** [comment] 2012-06-27 22:40
Hummm no way to fix it then eh...

**Comment by Philipp15b** [comment] 2012-07-17 17:57
Closing this now as I cannot fix it.

**Closed as completed by Philipp15b** 2012-07-17 17:57 UTC
Labels: invalid
