### ISSUE TITLE
Magicsigns 1.5.0 error at loading when sign created

### ISSUE THREAD

**Issue by Gotxi** [Philipp15b/MagicSigns#10] opened 2013-04-12 12:07 UTC
Hi again! this is what i have now:

1) Start the server, magicsigns loads correctly
2) I create a sign with this code [command] /say hello, sign works fine, server says hello
3) /stop server
4) open signs.db.yml, this is what is inside:

magic-signs:
- ==: de.philworld.bukkit.magicsigns.config.MagicSignSerializationProxy
  type: de.philworld.bukkit.magicsigns.signs.command.CommandSign
  z: 8
  y: 57
  world: palace
  x: -34

5) start server again
6) magic signs gives this error when trying to load:

2013-04-12 14:04:25 [SEVERE] Error occurred while enabling MagicSigns v1.5.0 (Is it up to date?)
java.lang.NullPointerException
    at org.bukkit.Location.getChunk(Location.java:73)
    at de.philworld.bukkit.magicsigns.SignLazyLoader.<init>(SignLazyLoader.java:26)
    at de.philworld.bukkit.magicsigns.MagicSigns.loadSigns(MagicSigns.java:227)
    at de.philworld.bukkit.magicsigns.MagicSigns.onEnable(MagicSigns.java:164)
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:217)
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:457)
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:383)
    at org.bukkit.craftbukkit.v1_5_R2.CraftServer.loadPlugin(CraftServer.java:305)
    at org.bukkit.craftbukkit.v1_5_R2.CraftServer.enablePlugins(CraftServer.java:287)
    at net.minecraft.server.v1_5_R2.MinecraftServer.j(MinecraftServer.java:309)
    at net.minecraft.server.v1_5_R2.MinecraftServer.e(MinecraftServer.java:288)
    at net.minecraft.server.v1_5_R2.MinecraftServer.a(MinecraftServer.java:248)
    at net.minecraft.server.v1_5_R2.DedicatedServer.init(DedicatedServer.java:154)
    at net.minecraft.server.v1_5_R2.MinecraftServer.run(MinecraftServer.java:387)
    at net.minecraft.server.v1_5_R2.ThreadServerApplication.run(SourceFile:573)

Using spigot:
14:08:52 [INFO] This server is running CraftBukkit version git-Spigot-771 (MC: 1.5.1) (Implementing API version 1.5.1-R0.2-SNAPSHOT)

Thanks in advanced again :)

**Comment by Philipp15b** [comment] 2013-04-12 12:52
Hi, it seems what I fixed did not fix the bug... Oh well. So as I see it, Spigot can't find the world that MagicSigns has saved in the config. I downloaded Spigot and tried to reproduce it, but it doesn't happen for me. [I created a debug build here](http://magicsigns.philworld.de/ms150-debug1.jar). Please paste the output.

**Comment by Gotxi** [comment] 2013-04-12 23:21
Hi again, im trying your debug build.

Content of signs.db.yml:

magic-signs:
- ==: de.philworld.bukkit.magicsigns.config.MagicSignSerializationProxy
  type: de.philworld.bukkit.magicsigns.signs.command.CommandSign
  z: 8
  y: 57
  world: palace
  x: -34

This is the console error when i start the server:

2013-04-13 01:15:13 [INFO] [MagicSigns] Enabling MagicSigns v1.5.0
2013-04-13 01:15:13 [SEVERE] [MagicSigns] Tried to get a location from a Proxy, but could not find world!
2013-04-13 01:15:13 [SEVERE] [MagicSigns] Saved world name is: 'palace' (6).
2013-04-13 01:15:13 [SEVERE] [MagicSigns] Available worlds:
2013-04-13 01:15:13 [SEVERE] [MagicSigns]  - 'survival' (8)
2013-04-13 01:15:13 [SEVERE] [MagicSigns]  - 'survival_nether' (15)
2013-04-13 01:15:13 [SEVERE] [MagicSigns]  - 'survival_the_end' (16)
2013-04-13 01:15:13 [SEVERE] Error occurred while enabling MagicSigns v1.5.0 (Is it up to date?)
java.lang.NullPointerException
    at de.philworld.bukkit.magicsigns.SignLazyLoader.<init>(SignLazyLoader.java:26)
    at de.philworld.bukkit.magicsigns.MagicSigns.loadSigns(MagicSigns.java:227)
    at de.philworld.bukkit.magicsigns.MagicSigns.onEnable(MagicSigns.java:164)
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:217)
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:457)
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:383)
    at org.bukkit.craftbukkit.v1_5_R2.CraftServer.loadPlugin(CraftServer.java:305)
    at org.bukkit.craftbukkit.v1_5_R2.CraftServer.enablePlugins(CraftServer.java:287)
    at net.minecraft.server.v1_5_R2.MinecraftServer.j(MinecraftServer.java:309)
    at net.minecraft.server.v1_5_R2.MinecraftServer.e(MinecraftServer.java:288)
    at net.minecraft.server.v1_5_R2.MinecraftServer.a(MinecraftServer.java:248)
    at net.minecraft.server.v1_5_R2.DedicatedServer.init(DedicatedServer.java:154)
    at net.minecraft.server.v1_5_R2.MinecraftServer.run(MinecraftServer.java:387)
    at net.minecraft.server.v1_5_R2.ThreadServerApplication.run(SourceFile:573)

Could be a "my worlds" plugin compatibility issue?

You could try it in your spigot server, you need these two:

My worlds:
http://ci.dj-tcraft.nl/job/MyWorlds/

BKcommonLib (dependecy):
http://ci.dj-tcraft.nl/job/BKCommonLib/

You can create worlds with /world create worldname and move between them with /world spawn worldname

Tell me if there is anything i can do to help you :)

**Comment by Philipp15b** [comment] 2013-04-13 12:31
Okay, I have resolved the issue. It was caused by unloaded worlds. Thanks for your help!

**Comment by Gotxi** [comment] 2013-04-13 13:19
Thanks to you to take the time to hear me and fix it.

I will wait for the next release :)

**Comment by Philipp15b** [comment] 2013-04-14 10:08
There's still something to be done to also allow unloading worlds while running MagicSigns. Reopening.

**Comment by Philipp15b** [comment] 2013-04-20 16:58
This is finally closed with 772ed65fd3a698ed1d3913383047966ec6a4b50c. Multiworld support will be included in MagicSigns 1.6.0 which will be released in a few hours on BukkitDev. Thanks for reporting!

**Closed as completed by Philipp15b** 2013-04-20 16:58 UTC

**Comment by Gotxi** [comment] 2013-04-20 17:03
Looking forward to test it, you're welcome :)
